#!/usr/bin/env bash
# This displays a string infinitely with a 2-second delay between each iteration

echo "Nz$" > /var/run/myscript.pid

hate_kill()
{
    echo "I hate the kill command"
}

no_love()
{
    echo "Y U no love me?!"
}

terminate()
{
    rm /var/run/myscript.pid
    exit
}

trap 'hate_kill && terminate' SIGTERM
trap no_love SIGINT
trap terminate SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
