#!/usr/bin/env bash
# This displays a string infinitely with a 2-second delay between each iteration
invincible()
{
    echo "I am invincible!!!"
}

trap invincible SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
